# Generated by Django 3.1.7 on 2021-03-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_card_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
