# Generated by Django 3.1.7 on 2021-03-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_table_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='name',
        ),
    ]
