# Generated by Django 3.1.7 on 2021-03-17 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_table'),
        ('order', '0004_remove_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.table'),
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
