# Generated by Django 3.1.7 on 2021-03-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promocode',
            field=models.CharField(blank=True, default=1, max_length=10, null=True),
        ),
    ]
