# Generated by Django 3.1.7 on 2021-03-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20210324_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='meal',
        ),
    ]
